Repository ENG1-Team-29/Assessment-2, pull requests merged in 2022-04, with the labels that each got.

#18 Unit tests & code refactoring
  README.md
  core/src/main/java/io/github/annabeths/Boats/AIBoat.java
  core/src/main/java/io/github/annabeths/Boats/AttackBoat.java
  core/src/main/java/io/github/annabeths/Boats/Boat.java
  core/src/main/java/io/github/annabeths/Boats/EnemyBoat.java
  core/src/main/java/io/github/annabeths/Boats/FriendlyBoat.java
  core/src/main/java/io/github/annabeths/Boats/NeutralBoat.java
  core/src/main/java/io/github/annabeths/Boats/PlayerBoat.java
  core/src/main/java/io/github/annabeths/Collectables/Powerup.java
  core/src/main/java/io/github/annabeths/Collectables/PowerupType.java
  core/src/main/java/io/github/annabeths/Colleges/College.java
  core/src/main/java/io/github/annabeths/Colleges/EnemyCollege.java
  core/src/main/java/io/github/annabeths/Colleges/PlayerCollege.java
  core/src/main/java/io/github/annabeths/GameGenerics/GameObject.java
  core/src/main/java/io/github/annabeths/GameScreens/GameController.java
  core/src/main/java/io/github/annabeths/GeneralControl/DebugUtils.java
  core/src/main/java/io/github/annabeths/GeneralControl/MathHelper.java
  core/src/main/java/io/github/annabeths/Level/GameMap.java
  core/src/main/java/io/github/annabeths/Projectiles/Projectile.java
  core/src/main/java/io/github/annabeths/Projectiles/ProjectileData.java
  core/src/main/java/io/github/annabeths/UI/HUD.java
  core/src/test/java/io/github/annabeths/Boats/AIBoatTest.java
  core/src/test/java/io/github/annabeths/Boats/AttackBoatTest.java
  core/src/test/java/io/github/annabeths/Boats/BoatTest.java
  core/src/test/java/io/github/annabeths/Boats/EnemyBoatTest.java
  core/src/test/java/io/github/annabeths/Boats/FriendlyBoatTest.java
  core/src/test/java/io/github/annabeths/Boats/GeneralBoatTests.java
  core/src/test/java/io/github/annabeths/Boats/NeutralBoatTest.java
  core/src/test/java/io/github/annabeths/Boats/PlayerBoatTest.java
  core/src/test/java/io/github/annabeths/Colleges/CollegeTest.java
  core/src/test/java/io/github/annabeths/Colleges/EnemyCollegeTest.java
  core/src/test/java/io/github/annabeths/Colleges/GenericCollegeTests.java
  core/src/test/java/io/github/annabeths/Colleges/PlayerCollegeTest.java
  core/src/test/java/io/github/annabeths/GameGenerics/GameObjectTest.java
  core/src/test/java/io/github/annabeths/GameGenerics/PhysicsObjectTest.java
  core/src/test/java/io/github/annabeths/GameScreens/GameControllerTest.java
  core/src/test/java/io/github/annabeths/GeneralControl/DebugUtilsTest.java
  core/src/test/java/io/github/annabeths/Projectiles/ProjectileRayTest.java
  core/src/test/java/io/github/annabeths/Projectiles/ProjectileTest.java
  core/src/test/java/io/github/annabeths/UI/HUDTest.java
  desktop/src/io/github/annabeths/desktop/DesktopLauncher.java
Labels: documentation, code rewrite

#20 Obstacles and Weather
  core/assets/img/entity/kraken1.png
  core/assets/img/entity/kraken2.png
  core/assets/img/entity/kraken3.png
  core/assets/img/entity/kraken_cannonball.png
  core/assets/img/entity/mine.png
  core/assets/img/entity/weather1.png
  core/assets/img/entity/weather2.png
  core/src/main/java/io/github/annabeths/Boats/AIBoat.java
  core/src/main/java/io/github/annabeths/Boats/PlayerBoat.java
  core/src/main/java/io/github/annabeths/GameScreens/GameController.java
  core/src/main/java/io/github/annabeths/GeneralControl/DebugUtils.java
  core/src/main/java/io/github/annabeths/GeneralControl/ResourceManager.java
  core/src/main/java/io/github/annabeths/Obstacles/Kraken.java
  core/src/main/java/io/github/annabeths/Obstacles/Mine.java
  core/src/main/java/io/github/annabeths/Obstacles/ObstacleEntity.java
  core/src/main/java/io/github/annabeths/Obstacles/Weather.java
  core/src/main/java/io/github/annabeths/Projectiles/ProjectileData.java
  core/src/main/java/io/github/annabeths/UI/HUD.java
  core/src/test/java/io/github/annabeths/Boats/NeutralBoatTest.java
  core/src/test/java/io/github/annabeths/GameScreens/GameControllerTest.java
Labels: enhancement

#21 Tests to ensure debugging is off when publishing
  build.gradle
  core/build.gradle
  core/src/main/java/io/github/annabeths/GeneralControl/DebugUtils.java
  core/src/main/java/io/github/annabeths/GeneralControl/debugsettings.xml
  core/src/main/java/io/github/annabeths/GeneralControl/eng1game.java
  core/src/test/java/io/github/annabeths/GeneralControl/DebugUtilsTest.java
  desktop/src/io/github/annabeths/desktop/DesktopLauncher.java
Labels: bug

#24 HUD Rewrite, XP Levels, and Powerup Usage Changes
  core/assets/audio/powerups/attribution.md
  core/assets/audio/powerups/burst-fire.mp3
  core/assets/audio/powerups/damage-buff.mp3
  core/assets/audio/powerups/invincibility.mp3
  core/assets/audio/powerups/rapid-fire.mp3
  core/assets/audio/powerups/speed-boost.mp3
  core/assets/audio/splash/bruh.mp3
  core/assets/audio/splash/ding.mp3
  core/assets/mario/shardlogo.webm
  core/assets/ui/button.png
  core/assets/ui/hud-ui.png
  core/assets/ui/hud-ui.xcf
  core/assets/ui/instructions.png
  core/assets/ui/instructions.xcf
  core/src/main/java/io/github/annabeths/Boats/EnemyBoat.java
  core/src/main/java/io/github/annabeths/Boats/NeutralBoat.java
  core/src/main/java/io/github/annabeths/Boats/PlayerBoat.java
  core/src/main/java/io/github/annabeths/Collectables/Powerup.java
  core/src/main/java/io/github/annabeths/Collectables/PowerupType.java
  core/src/main/java/io/github/annabeths/GameScreens/GameController.java
  core/src/main/java/io/github/annabeths/GameScreens/GameOverScreen.java
  core/src/main/java/io/github/annabeths/GameScreens/GameWinScreen.java
  core/src/main/java/io/github/annabeths/GameScreens/Menu.java
  core/src/main/java/io/github/annabeths/GameScreens/Splash.java
  core/src/main/java/io/github/annabeths/GeneralControl/DebugUtils.java
  core/src/main/java/io/github/annabeths/GeneralControl/MathHelper.java
  core/src/main/java/io/github/annabeths/GeneralControl/ResourceManager.java
  core/src/main/java/io/github/annabeths/GeneralControl/debugsettings.xml
  core/src/main/java/io/github/annabeths/GeneralControl/eng1game.java
  core/src/main/java/io/github/annabeths/Obstacles/Kraken.java
  core/src/main/java/io/github/annabeths/Obstacles/ObstacleEntity.java
  core/src/main/java/io/github/annabeths/Obstacles/Weather.java
  core/src/main/java/io/github/annabeths/UI/HUD.java
  core/src/test/java/io/github/annabeths/Boats/EnemyBoatTest.java
  core/src/test/java/io/github/annabeths/Boats/NeutralBoatTest.java
  core/src/test/java/io/github/annabeths/Boats/PlayerBoatTest.java
  core/src/test/java/io/github/annabeths/GameScreens/GameControllerTest.java
  core/src/test/java/io/github/annabeths/GameScreens/GameOverScreenTest.java
  core/src/test/java/io/github/annabeths/GameScreens/GameWinScreenTest.java
  core/src/test/java/io/github/annabeths/GameScreens/MenuTest.java
  core/src/test/java/io/github/annabeths/GameScreens/SplashTest.java
  core/src/test/java/io/github/annabeths/GeneralControl/DebugUtilsTest.java
  core/src/test/java/io/github/annabeths/GeneralControl/ResourceManagerTest.java
  core/src/test/java/io/github/annabeths/GeneralControl/TestHelper.java
  core/src/test/java/io/github/annabeths/Level/GameMapTest.java
  core/src/test/java/io/github/annabeths/Level/WaterBackgroundTest.java
  core/src/test/java/io/github/annabeths/UI/HUDTest.java
  desktop/src/io/github/annabeths/desktop/DesktopLauncher.java
Labels: bug, code rewrite

#25 Plunder Spending
  core/assets/ui/instructions.png
  core/assets/ui/instructions.xcf
  core/src/main/java/io/github/annabeths/GameScreens/GameController.java
  core/src/main/java/io/github/annabeths/UI/HUD.java
  core/src/test/java/io/github/annabeths/UI/HUDTest.java
Labels: enhancement

#28 Further Unit Testing
  core/src/main/java/io/github/annabeths/Collectables/Powerup.java
  core/src/main/java/io/github/annabeths/GameScreens/GameController.java
  core/src/main/java/io/github/annabeths/GameScreens/GameDifScreen.java
  core/src/main/java/io/github/annabeths/GeneralControl/ResourceManager.java
  core/src/main/java/io/github/annabeths/GeneralControl/eng1game.java
  core/src/main/java/io/github/annabeths/Obstacles/Kraken.java
  core/src/main/java/io/github/annabeths/Obstacles/Mine.java
  core/src/main/java/io/github/annabeths/Obstacles/ObstacleEntity.java
  core/src/main/java/io/github/annabeths/Obstacles/Weather.java
  core/src/main/java/io/github/annabeths/UI/HUD.java
  core/src/test/java/io/github/annabeths/Collectables/PowerupTest.java
  core/src/test/java/io/github/annabeths/GameScreens/GameControllerTest.java
  core/src/test/java/io/github/annabeths/GameScreens/GameDifScreenTest.java
  core/src/test/java/io/github/annabeths/GameScreens/SplashTest.java
  core/src/test/java/io/github/annabeths/GeneralControl/TestHelper.java
  core/src/test/java/io/github/annabeths/GeneralControl/eng1gameTest.java
  core/src/test/java/io/github/annabeths/Obstacles/KrakenTest.java
  core/src/test/java/io/github/annabeths/Obstacles/WeatherTest.java
  core/src/test/java/io/github/annabeths/UI/HUDTest.java
Labels: documentation, testing

#29 Bug fixes
  core/assets/ui/instructions.png
  core/assets/ui/instructions.xcf
  core/src/main/java/io/github/annabeths/Boats/EnemyBoat.java
  core/src/main/java/io/github/annabeths/Boats/NeutralBoat.java
  core/src/main/java/io/github/annabeths/Boats/PlayerBoat.java
  core/src/main/java/io/github/annabeths/Collectables/PowerupType.java
  core/src/main/java/io/github/annabeths/Colleges/EnemyCollege.java
  core/src/main/java/io/github/annabeths/GameGenerics/GameObject.java
  core/src/main/java/io/github/annabeths/GameScreens/GameController.java
  core/src/main/java/io/github/annabeths/GameScreens/GameDifScreen.java
  core/src/main/java/io/github/annabeths/GameScreens/GameOverScreen.java
  core/src/main/java/io/github/annabeths/GameScreens/GameWinScreen.java
  core/src/main/java/io/github/annabeths/GameScreens/Menu.java
  core/src/main/java/io/github/annabeths/GeneralControl/ResourceManager.java
  core/src/main/java/io/github/annabeths/GeneralControl/eng1game.java
  core/src/main/java/io/github/annabeths/Obstacles/Kraken.java
  core/src/main/java/io/github/annabeths/Obstacles/Mine.java
  core/src/main/java/io/github/annabeths/Obstacles/Weather.java
  core/src/test/java/io/github/annabeths/Boats/PlayerBoatTest.java
  core/src/test/java/io/github/annabeths/GameScreens/GameControllerTest.java
  core/src/test/java/io/github/annabeths/GameScreens/GameDifScreenTest.java
  core/src/test/java/io/github/annabeths/Obstacles/MineTest.java
  core/src/test/java/io/github/annabeths/Obstacles/WeatherTest.java
Labels: bug, code rewrite
